### ISSUE TITLE
TrueNAS reports failed SMART test after SAS drives spun down

### ISSUE THREAD

**Issue by charlie0129** [ngandrass/truenas-spindown-timer#11] opened 2022-03-28 18:15 UTC
After my SAS drive spun down, TrueNAS sent alerts to my email:
```
Current alerts:
* Device: /dev/da2, failed to read SMART values.
* Device: /dev/da2, Read SMART Self-Test Log Failed.
```

Although I know the drive itself is fine (if I double check it manually), it frustrate me a little because I feel like to double check if it is actually the case.

I assume this is because SAS drives don't have a `standby`-equivalent mode like SATA drives do. If SAS drives are stopped, they act like `sleep` mode in SATA drives. (please correct me if I am wrong)

Of course, I can disable SMART tests (and I probably will). I just want to know if there is a way to avoid these (false) alerts.

Also, the code that tests whether a SCSI drive has spun down seems not to be working (line 223).
Here is the output after da2 (SAS drive) has spun down (return code: 1):
```
# camcontrol modepage da2 -m 0x1a
camcontrol: mode sense command returned error
```

SATA drives don't have the above issues.

**Comment by ngandrass** [comment] 2022-04-09 11:23
Unfortunately I only use TrueNAS for home use with SATA drives, so we have to do a little remote debugging here...

- What drives and SCSI controller are you using?
- What is the output of `smartctl -a /dev/da2` for a **spinning and a spun down** drive? On my SATA drives it works fine for both spinning and spun down drives.
- What is the output of `camcontrol modepage da2 -m 0x1a` for a **spinning and a spun down** drive?

According to `/usr/share/misc/scsi_modes` the page `0x1a` should contain all power information. Just a first guess: Maybe your controller or drive does not expose this information correctly? If this is the case, we have two options:

1. Find a workaround to determine whether the drive is spinning or not.
2. Report drives without power information as always spinning. This causes the spindown command to be issued every `POLL_TIME` seconds after `TIMEOUT` is elapsed for the drive. Should in theory not hurt??

**Comment by ngandrass** [comment] 2022-04-09 11:27
Quick followup regarding the alerts: If not configured as described in the README the S.M.A.R.T. tests should wake the device. Reading the S.M.A.R.T. info however, should work regardless of this setting.

**Comment by charlie0129** [comment] 2022-04-09 14:32
Thanks for your advice! I have indeed configured according to README.

Drive Model: `Seagate ST6000NM0034`

SAS Controller: `LSI SAS2308` (IT Mode)

`smartctl -a /dev/da2`:

<details>
<summary>Spinning drive:</summary>

```console
# smartctl -a /dev/da2
smartctl 7.2 2020-12-30 r5155 [FreeBSD 12.2-RELEASE-p12 amd64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST6000NM0034
Revision:             E0G5
Compliance:           SPC-4
User Capacity:        6,001,175,126,016 bytes [6.00 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Formatted with type 2 protection
8 bytes of protection information per logical block
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c5008e9c2d6b
Serial number:        S4D0A2BQ0000K605HSRT
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sat Apr  9 22:16:49 2022 CST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Grown defects during certification <not available>
Total blocks reassigned during format <not available>
Total new blocks reassigned <not available>
Power on minutes since format <not available>
Current Drive Temperature:     33 C
Drive Trip Temperature:        60 C

Accumulated power on time, hours:minutes 42055:41
Manufactured in week 35 of year 2015
Specified cycle count over device lifetime:  10000
Accumulated start-stop cycles:  63
Specified load-unload count over device lifetime:  300000
Accumulated load-unload cycles:  12238
Elements in grown defect list: 0

Vendor (Seagate Cache) information
  Blocks sent to initiator = 32830912
  Blocks received from initiator = 3232016
  Blocks read from cache and sent to initiator = 168268
  Number of read and write commands whose size <= segment size = 243968
  Number of read and write commands whose size > segment size = 0

Vendor (Seagate/Hitachi) factory information
  number of hours powered up = 42055.68
  number of minutes until next internal SMART test = 50

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:    5841152        0         0   5841152          0         17.072           0
write:         0        0         0         0          0          2.187           0

Non-medium error count:        0


[GLTSD (Global Logging Target Save Disable) set. Enable Save with '-S on']
SMART Self-test log
Num  Test              Status                 segment  LifeTime  LBA_first_err [SK ASC ASQ]
     Description                              number   (hours)
# 1  Background long   Completed                   -   40828                 - [-   -    -]
# 2  Background long   Aborted (by user command)   -   40817                 - [-   -    -]
# 3  Background short  Completed                   -   40816                 - [-   -    -]
# 4  Background long   Aborted (by user command)   -   40816                 - [-   -    -]
# 5  Background short  Aborted (by user command)   -      84                 - [-   -    -]
# 6  Background short  Completed                   -      84                 - [-   -    -]

Long (extended) Self-test duration: 39977 seconds [666.3 minutes]
```
</details>

<details>
<summary>Spun down drive:</summary>

```console
# smartctl -a /dev/da2
smartctl 7.2 2020-12-30 r5155 [FreeBSD 12.2-RELEASE-p12 amd64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST6000NM0034
Revision:             E0G5
Compliance:           SPC-4
User Capacity:        6,001,175,126,016 bytes [6.00 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Formatted with type 2 protection
8 bytes of protection information per logical block
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c5008e9c2d6b
Serial number:        S4D0A2BQ0000K605HSRT
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sat Apr  9 22:23:03 2022 CST
device is NOT READY (e.g. spun down, busy)
A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.
```
</details>

`camcontrol modepage da2 -m 0x1a`:

<details>
<summary>Spinning drive:</summary>

```console
# camcontrol modepage da2 -m 0x1a
PM_BG_PRECEDENCE:  0
STANDBY_Y:  0
IDLE_C:  0
IDLE_B:  1
IDLE_A:  1
STANDBY_Z:  0
IDLE_A Condition Timer:  1200
STANDBY_Z Condition Timer:  9000
IDLE_B Condition Timer:  2400
IDLE_C Condition Timer:  6000
STANDBY_Y Condition Timer:  6000
CCF Idle:  1
CCF Standby:  1
CCF Stopped:  2
```
</details>

<details>
<summary>Spun down drive:</summary>

```console
# camcontrol modepage da2 -m 0x1a
camcontrol: mode sense command returned error
```
</details>

It seems that `0x1a` is not reported with a spun down SAS drive.

**Comment by ngandrass** [comment] 2022-04-10 12:27
Thanks for all the information!

Seems like either your drive or SAS controller does not respond properly to commands when the drive is in standby mode. I think that the disk controller probably is the problem, since @bilditup1 successfully used the script with an LSI 2308 (see: https://github.com/ngandrass/truenas-spindown-timer/pull/2) in the past.

I checked the [manual for your drive](https://www.seagate.com/files/www-content/product-content/enterprise-hdd-fam/enterprise-capacity-3-5-hdd/constellation-es-4/en-us/docs/100726011g.pdf) but couldn't find any note on modepages being unavailable in certain power modes. It moreover confirmed 0x1A to be correct...

I do not really have an idea how to solve this issue. But out of curiosity: What is the content of the "Power Condition Vital Product Data (VPD) Page (VPD page 0x8A)"? You should be able to read it via `camcontrol modepage da2 -m 0x8a`

**Comment by charlie0129** [comment] 2022-04-10 14:20
Reading `0x8a` returned `camcontrol: invalid mode page 138`.

Now it seems like no quick solution can be found. I don't have more controllers or different drive models to test with. I will probably just let the drive spinning anyway. Thank you for your attention.

**Comment by ngandrass** [comment] 2022-04-11 11:38
So it looks like the issue really is related to the drives themselves or the specific combination of drives with the LSI 2308... I'm sorry that I cannot provide a quick solution to your problem.

I'll close the issue for now but please feel free to re-open it when you find new information or even got it working properly :)

**Closed by ngandrass** 2022-04-11 11:38 UTC
